# CMake generated Testfile for 
# Source directory: /Users/kevinzhou/Github/Firmware/platforms/posix
# Build directory: /Users/kevinzhou/Github/Firmware/platforms/posix
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(autodeclination "/Users/kevinzhou/Github/Firmware/Tools/sitl_run.sh" "/Users/kevinzhou/Github/Firmware/px4" "posix-configs/SITL/init/test" "none" "none" "tests_autodeclination_generated" "/Users/kevinzhou/Github/Firmware" "/Users/kevinzhou/Github/Firmware")
set_tests_properties(autodeclination PROPERTIES  FAIL_REGULAR_EXPRESSION "autodeclination FAILED" PASS_REGULAR_EXPRESSION "autodeclination PASSED" WORKING_DIRECTORY "/Users/kevinzhou/Github/Firmware/tmp")
add_test(bson "/Users/kevinzhou/Github/Firmware/Tools/sitl_run.sh" "/Users/kevinzhou/Github/Firmware/px4" "posix-configs/SITL/init/test" "none" "none" "tests_bson_generated" "/Users/kevinzhou/Github/Firmware" "/Users/kevinzhou/Github/Firmware")
set_tests_properties(bson PROPERTIES  FAIL_REGULAR_EXPRESSION "bson FAILED" PASS_REGULAR_EXPRESSION "bson PASSED" WORKING_DIRECTORY "/Users/kevinzhou/Github/Firmware/tmp")
add_test(commander "/Users/kevinzhou/Github/Firmware/Tools/sitl_run.sh" "/Users/kevinzhou/Github/Firmware/px4" "posix-configs/SITL/init/test" "none" "none" "tests_commander_generated" "/Users/kevinzhou/Github/Firmware" "/Users/kevinzhou/Github/Firmware")
set_tests_properties(commander PROPERTIES  FAIL_REGULAR_EXPRESSION "commander FAILED" PASS_REGULAR_EXPRESSION "commander PASSED" WORKING_DIRECTORY "/Users/kevinzhou/Github/Firmware/tmp")
add_test(controllib "/Users/kevinzhou/Github/Firmware/Tools/sitl_run.sh" "/Users/kevinzhou/Github/Firmware/px4" "posix-configs/SITL/init/test" "none" "none" "tests_controllib_generated" "/Users/kevinzhou/Github/Firmware" "/Users/kevinzhou/Github/Firmware")
set_tests_properties(controllib PROPERTIES  FAIL_REGULAR_EXPRESSION "controllib FAILED" PASS_REGULAR_EXPRESSION "controllib PASSED" WORKING_DIRECTORY "/Users/kevinzhou/Github/Firmware/tmp")
add_test(conv "/Users/kevinzhou/Github/Firmware/Tools/sitl_run.sh" "/Users/kevinzhou/Github/Firmware/px4" "posix-configs/SITL/init/test" "none" "none" "tests_conv_generated" "/Users/kevinzhou/Github/Firmware" "/Users/kevinzhou/Github/Firmware")
set_tests_properties(conv PROPERTIES  FAIL_REGULAR_EXPRESSION "conv FAILED" PASS_REGULAR_EXPRESSION "conv PASSED" WORKING_DIRECTORY "/Users/kevinzhou/Github/Firmware/tmp")
add_test(ctlmath "/Users/kevinzhou/Github/Firmware/Tools/sitl_run.sh" "/Users/kevinzhou/Github/Firmware/px4" "posix-configs/SITL/init/test" "none" "none" "tests_ctlmath_generated" "/Users/kevinzhou/Github/Firmware" "/Users/kevinzhou/Github/Firmware")
set_tests_properties(ctlmath PROPERTIES  FAIL_REGULAR_EXPRESSION "ctlmath FAILED" PASS_REGULAR_EXPRESSION "ctlmath PASSED" WORKING_DIRECTORY "/Users/kevinzhou/Github/Firmware/tmp")
add_test(dataman "/Users/kevinzhou/Github/Firmware/Tools/sitl_run.sh" "/Users/kevinzhou/Github/Firmware/px4" "posix-configs/SITL/init/test" "none" "none" "tests_dataman_generated" "/Users/kevinzhou/Github/Firmware" "/Users/kevinzhou/Github/Firmware")
set_tests_properties(dataman PROPERTIES  FAIL_REGULAR_EXPRESSION "dataman FAILED" PASS_REGULAR_EXPRESSION "dataman PASSED" WORKING_DIRECTORY "/Users/kevinzhou/Github/Firmware/tmp")
add_test(file2 "/Users/kevinzhou/Github/Firmware/Tools/sitl_run.sh" "/Users/kevinzhou/Github/Firmware/px4" "posix-configs/SITL/init/test" "none" "none" "tests_file2_generated" "/Users/kevinzhou/Github/Firmware" "/Users/kevinzhou/Github/Firmware")
set_tests_properties(file2 PROPERTIES  FAIL_REGULAR_EXPRESSION "file2 FAILED" PASS_REGULAR_EXPRESSION "file2 PASSED" WORKING_DIRECTORY "/Users/kevinzhou/Github/Firmware/tmp")
add_test(float "/Users/kevinzhou/Github/Firmware/Tools/sitl_run.sh" "/Users/kevinzhou/Github/Firmware/px4" "posix-configs/SITL/init/test" "none" "none" "tests_float_generated" "/Users/kevinzhou/Github/Firmware" "/Users/kevinzhou/Github/Firmware")
set_tests_properties(float PROPERTIES  FAIL_REGULAR_EXPRESSION "float FAILED" PASS_REGULAR_EXPRESSION "float PASSED" WORKING_DIRECTORY "/Users/kevinzhou/Github/Firmware/tmp")
add_test(gpio "/Users/kevinzhou/Github/Firmware/Tools/sitl_run.sh" "/Users/kevinzhou/Github/Firmware/px4" "posix-configs/SITL/init/test" "none" "none" "tests_gpio_generated" "/Users/kevinzhou/Github/Firmware" "/Users/kevinzhou/Github/Firmware")
set_tests_properties(gpio PROPERTIES  FAIL_REGULAR_EXPRESSION "gpio FAILED" PASS_REGULAR_EXPRESSION "gpio PASSED" WORKING_DIRECTORY "/Users/kevinzhou/Github/Firmware/tmp")
add_test(hrt "/Users/kevinzhou/Github/Firmware/Tools/sitl_run.sh" "/Users/kevinzhou/Github/Firmware/px4" "posix-configs/SITL/init/test" "none" "none" "tests_hrt_generated" "/Users/kevinzhou/Github/Firmware" "/Users/kevinzhou/Github/Firmware")
set_tests_properties(hrt PROPERTIES  FAIL_REGULAR_EXPRESSION "hrt FAILED" PASS_REGULAR_EXPRESSION "hrt PASSED" WORKING_DIRECTORY "/Users/kevinzhou/Github/Firmware/tmp")
add_test(int "/Users/kevinzhou/Github/Firmware/Tools/sitl_run.sh" "/Users/kevinzhou/Github/Firmware/px4" "posix-configs/SITL/init/test" "none" "none" "tests_int_generated" "/Users/kevinzhou/Github/Firmware" "/Users/kevinzhou/Github/Firmware")
set_tests_properties(int PROPERTIES  FAIL_REGULAR_EXPRESSION "int FAILED" PASS_REGULAR_EXPRESSION "int PASSED" WORKING_DIRECTORY "/Users/kevinzhou/Github/Firmware/tmp")
add_test(mathlib "/Users/kevinzhou/Github/Firmware/Tools/sitl_run.sh" "/Users/kevinzhou/Github/Firmware/px4" "posix-configs/SITL/init/test" "none" "none" "tests_mathlib_generated" "/Users/kevinzhou/Github/Firmware" "/Users/kevinzhou/Github/Firmware")
set_tests_properties(mathlib PROPERTIES  FAIL_REGULAR_EXPRESSION "mathlib FAILED" PASS_REGULAR_EXPRESSION "mathlib PASSED" WORKING_DIRECTORY "/Users/kevinzhou/Github/Firmware/tmp")
add_test(matrix "/Users/kevinzhou/Github/Firmware/Tools/sitl_run.sh" "/Users/kevinzhou/Github/Firmware/px4" "posix-configs/SITL/init/test" "none" "none" "tests_matrix_generated" "/Users/kevinzhou/Github/Firmware" "/Users/kevinzhou/Github/Firmware")
set_tests_properties(matrix PROPERTIES  FAIL_REGULAR_EXPRESSION "matrix FAILED" PASS_REGULAR_EXPRESSION "matrix PASSED" WORKING_DIRECTORY "/Users/kevinzhou/Github/Firmware/tmp")
add_test(mavlink "/Users/kevinzhou/Github/Firmware/Tools/sitl_run.sh" "/Users/kevinzhou/Github/Firmware/px4" "posix-configs/SITL/init/test" "none" "none" "tests_mavlink_generated" "/Users/kevinzhou/Github/Firmware" "/Users/kevinzhou/Github/Firmware")
set_tests_properties(mavlink PROPERTIES  FAIL_REGULAR_EXPRESSION "mavlink FAILED" PASS_REGULAR_EXPRESSION "mavlink PASSED" WORKING_DIRECTORY "/Users/kevinzhou/Github/Firmware/tmp")
add_test(mc_pos_control "/Users/kevinzhou/Github/Firmware/Tools/sitl_run.sh" "/Users/kevinzhou/Github/Firmware/px4" "posix-configs/SITL/init/test" "none" "none" "tests_mc_pos_control_generated" "/Users/kevinzhou/Github/Firmware" "/Users/kevinzhou/Github/Firmware")
set_tests_properties(mc_pos_control PROPERTIES  FAIL_REGULAR_EXPRESSION "mc_pos_control FAILED" PASS_REGULAR_EXPRESSION "mc_pos_control PASSED" WORKING_DIRECTORY "/Users/kevinzhou/Github/Firmware/tmp")
add_test(param "/Users/kevinzhou/Github/Firmware/Tools/sitl_run.sh" "/Users/kevinzhou/Github/Firmware/px4" "posix-configs/SITL/init/test" "none" "none" "tests_param_generated" "/Users/kevinzhou/Github/Firmware" "/Users/kevinzhou/Github/Firmware")
set_tests_properties(param PROPERTIES  FAIL_REGULAR_EXPRESSION "param FAILED" PASS_REGULAR_EXPRESSION "param PASSED" WORKING_DIRECTORY "/Users/kevinzhou/Github/Firmware/tmp")
add_test(parameters "/Users/kevinzhou/Github/Firmware/Tools/sitl_run.sh" "/Users/kevinzhou/Github/Firmware/px4" "posix-configs/SITL/init/test" "none" "none" "tests_parameters_generated" "/Users/kevinzhou/Github/Firmware" "/Users/kevinzhou/Github/Firmware")
set_tests_properties(parameters PROPERTIES  FAIL_REGULAR_EXPRESSION "parameters FAILED" PASS_REGULAR_EXPRESSION "parameters PASSED" WORKING_DIRECTORY "/Users/kevinzhou/Github/Firmware/tmp")
add_test(perf "/Users/kevinzhou/Github/Firmware/Tools/sitl_run.sh" "/Users/kevinzhou/Github/Firmware/px4" "posix-configs/SITL/init/test" "none" "none" "tests_perf_generated" "/Users/kevinzhou/Github/Firmware" "/Users/kevinzhou/Github/Firmware")
set_tests_properties(perf PROPERTIES  FAIL_REGULAR_EXPRESSION "perf FAILED" PASS_REGULAR_EXPRESSION "perf PASSED" WORKING_DIRECTORY "/Users/kevinzhou/Github/Firmware/tmp")
add_test(rc "/Users/kevinzhou/Github/Firmware/Tools/sitl_run.sh" "/Users/kevinzhou/Github/Firmware/px4" "posix-configs/SITL/init/test" "none" "none" "tests_rc_generated" "/Users/kevinzhou/Github/Firmware" "/Users/kevinzhou/Github/Firmware")
set_tests_properties(rc PROPERTIES  FAIL_REGULAR_EXPRESSION "rc FAILED" PASS_REGULAR_EXPRESSION "rc PASSED" WORKING_DIRECTORY "/Users/kevinzhou/Github/Firmware/tmp")
add_test(servo "/Users/kevinzhou/Github/Firmware/Tools/sitl_run.sh" "/Users/kevinzhou/Github/Firmware/px4" "posix-configs/SITL/init/test" "none" "none" "tests_servo_generated" "/Users/kevinzhou/Github/Firmware" "/Users/kevinzhou/Github/Firmware")
set_tests_properties(servo PROPERTIES  FAIL_REGULAR_EXPRESSION "servo FAILED" PASS_REGULAR_EXPRESSION "servo PASSED" WORKING_DIRECTORY "/Users/kevinzhou/Github/Firmware/tmp")
add_test(sf0x "/Users/kevinzhou/Github/Firmware/Tools/sitl_run.sh" "/Users/kevinzhou/Github/Firmware/px4" "posix-configs/SITL/init/test" "none" "none" "tests_sf0x_generated" "/Users/kevinzhou/Github/Firmware" "/Users/kevinzhou/Github/Firmware")
set_tests_properties(sf0x PROPERTIES  FAIL_REGULAR_EXPRESSION "sf0x FAILED" PASS_REGULAR_EXPRESSION "sf0x PASSED" WORKING_DIRECTORY "/Users/kevinzhou/Github/Firmware/tmp")
add_test(sleep "/Users/kevinzhou/Github/Firmware/Tools/sitl_run.sh" "/Users/kevinzhou/Github/Firmware/px4" "posix-configs/SITL/init/test" "none" "none" "tests_sleep_generated" "/Users/kevinzhou/Github/Firmware" "/Users/kevinzhou/Github/Firmware")
set_tests_properties(sleep PROPERTIES  FAIL_REGULAR_EXPRESSION "sleep FAILED" PASS_REGULAR_EXPRESSION "sleep PASSED" WORKING_DIRECTORY "/Users/kevinzhou/Github/Firmware/tmp")
add_test(versioning "/Users/kevinzhou/Github/Firmware/Tools/sitl_run.sh" "/Users/kevinzhou/Github/Firmware/px4" "posix-configs/SITL/init/test" "none" "none" "tests_versioning_generated" "/Users/kevinzhou/Github/Firmware" "/Users/kevinzhou/Github/Firmware")
set_tests_properties(versioning PROPERTIES  FAIL_REGULAR_EXPRESSION "versioning FAILED" PASS_REGULAR_EXPRESSION "versioning PASSED" WORKING_DIRECTORY "/Users/kevinzhou/Github/Firmware/tmp")
add_test(posix_hello "/Users/kevinzhou/Github/Firmware/Tools/sitl_run.sh" "/Users/kevinzhou/Github/Firmware/px4" "posix-configs/SITL/init/test" "none" "none" "cmd_hello_generated" "/Users/kevinzhou/Github/Firmware" "/Users/kevinzhou/Github/Firmware")
set_tests_properties(posix_hello PROPERTIES  PASS_REGULAR_EXPRESSION "Shutting down" WORKING_DIRECTORY "/Users/kevinzhou/Github/Firmware/tmp")
add_test(posix_hrt_test "/Users/kevinzhou/Github/Firmware/Tools/sitl_run.sh" "/Users/kevinzhou/Github/Firmware/px4" "posix-configs/SITL/init/test" "none" "none" "cmd_hrt_test_generated" "/Users/kevinzhou/Github/Firmware" "/Users/kevinzhou/Github/Firmware")
set_tests_properties(posix_hrt_test PROPERTIES  PASS_REGULAR_EXPRESSION "Shutting down" WORKING_DIRECTORY "/Users/kevinzhou/Github/Firmware/tmp")
add_test(posix_muorb_test "/Users/kevinzhou/Github/Firmware/Tools/sitl_run.sh" "/Users/kevinzhou/Github/Firmware/px4" "posix-configs/SITL/init/test" "none" "none" "cmd_muorb_test_generated" "/Users/kevinzhou/Github/Firmware" "/Users/kevinzhou/Github/Firmware")
set_tests_properties(posix_muorb_test PROPERTIES  PASS_REGULAR_EXPRESSION "Shutting down" WORKING_DIRECTORY "/Users/kevinzhou/Github/Firmware/tmp")
add_test(posix_vcdev_test "/Users/kevinzhou/Github/Firmware/Tools/sitl_run.sh" "/Users/kevinzhou/Github/Firmware/px4" "posix-configs/SITL/init/test" "none" "none" "cmd_vcdev_test_generated" "/Users/kevinzhou/Github/Firmware" "/Users/kevinzhou/Github/Firmware")
set_tests_properties(posix_vcdev_test PROPERTIES  PASS_REGULAR_EXPRESSION "Shutting down" WORKING_DIRECTORY "/Users/kevinzhou/Github/Firmware/tmp")
add_test(posix_wqueue_test "/Users/kevinzhou/Github/Firmware/Tools/sitl_run.sh" "/Users/kevinzhou/Github/Firmware/px4" "posix-configs/SITL/init/test" "none" "none" "cmd_wqueue_test_generated" "/Users/kevinzhou/Github/Firmware" "/Users/kevinzhou/Github/Firmware")
set_tests_properties(posix_wqueue_test PROPERTIES  PASS_REGULAR_EXPRESSION "Shutting down" WORKING_DIRECTORY "/Users/kevinzhou/Github/Firmware/tmp")
subdirs("src")
